project:
  type: website
  output-dir: html
  render:
    - 1_landforms.qmd
    - 2_elevation_range.qmd  
    - 3_wetland_score.qmd
    - 4_soil_diversity.qmd
    - 5_Z_scores.qmd
   
  
website: 
  navbar:
    left:
      - text: Tutoriais
        menu:
         - text: Heterogeneidade da paisagem
         - text: Resistência da paisagem
           href: https://resiliencia-climatica-brasil.github.io/Resistencia/
         - text: Conectividade local 
         - text: Resiliência da paisagem  
      - text: Downloads
        href: https://projeto-resiliencia-tnc.hub.arcgis.com        
  sidebar: 
    title: "Mapeamento de áreas resilientes a mudanças climáticas nos biomas brasileiros" 
    logo: figs/1667403883848_theme_logo.png     
    style: "docked"
    contents:
      - section: "Sumário"
        contents:
          - 1_landforms.qmd
          - 2_elevation_range.qmd   
          - 3_wetland_score.qmd
          - 4_soil_diversity.qmd
          - 5_Z_scores.qmd
              
  page-navigation: true
  favicon: figs/1667403883848_theme_logo.png
bibliography: bibliografia.bib
csl: citation_style.csl
lang: pt-br
format:
  html:
    theme: default
    css: styles.css   

